version: '3.1'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    # ports:
    #   - "3000:3000"
    env_file:
      - ./frontend/.env

  nginx:
    depends_on:
      - backend
      - frontend
    build: ./nginx
    ports:
      - "8000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  # nginx:
  #   depends_on:
  #     - frontend
  #     - backend
  #   image: nginx
  #   ports:
  #     - "8000:80"
  #   volumes:
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf